spring:
  datasource:
    url: jdbc:mysql://localhost:3307/food_delivery
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    context-path: /api
#@ConfigurationProperties: Tu map key ben application thanh doi tuong
#@Value(${tenkey}): lay gia tri key ben application thanh bien
file:
  upload-dir: \Users\KenPham\OneDrive - Vision Center Network of America\Desktop\images